### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by JakobMiksch** [geoext/geoext3-ws#33]
I tried to run the workshop with `npm install` and `npm start`, but I receive an error. Below you can find the error log.

Do you have an idea what is wrong there?

my command:

```
sudo npm start

> geoext3-ws@0.0.1 start /home/joe/Downloads/geoext3-ws-master
> mkdirp src/_book && parallelshell "node scripts/sync-exercises.js" "npm run doc:serve"

child_process.js:403
    throw new TypeError('"cwd" must be a string');
    ^

TypeError: "cwd" must be a string
    at normalizeSpawnArguments (child_process.js:403:11)
    at exports.spawn (child_process.js:496:38)
    at /home/joe/Downloads/geoext3-ws-master/node_modules/parallelshell/index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/joe/Downloads/geoext3-ws-master/node_modules/parallelshell/index.js:100:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geoext3-ws@0.0.1 start: `mkdirp src/_book && parallelshell "node scripts/sync-exercises.js" "npm run doc:serve"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geoext3-ws@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joe/.npm/_logs/2018-05-24T15_57_19_413Z-debug.log
```

Error log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.1.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle geoext3-ws@0.0.1~prestart: geoext3-ws@0.0.1
6 info lifecycle geoext3-ws@0.0.1~start: geoext3-ws@0.0.1
7 verbose lifecycle geoext3-ws@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle geoext3-ws@0.0.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/joe/Downloads/geoext3-ws-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle geoext3-ws@0.0.1~start: CWD: /home/joe/Downloads/geoext3-ws-master
10 silly lifecycle geoext3-ws@0.0.1~start: Args: [ '-c',
10 silly lifecycle   'mkdirp src/_book && parallelshell "node scripts/sync-exercises.js" "npm run doc:serve"' ]
11 silly lifecycle geoext3-ws@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle geoext3-ws@0.0.1~start: Failed to exec start script
13 verbose stack Error: geoext3-ws@0.0.1 start: `mkdirp src/_book && parallelshell "node scripts/sync-exercises.js" "npm run doc:serve"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid geoext3-ws@0.0.1
15 verbose cwd /home/joe/Downloads/geoext3-ws-master
16 verbose Linux 4.13.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.2
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error geoext3-ws@0.0.1 start: `mkdirp src/_book && parallelshell "node scripts/sync-exercises.js" "npm run doc:serve"`
22 error Exit status 1
23 error Failed at the geoext3-ws@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by marcjansen** [comment]
Please do not run `npm` stuff under `sudo` rights. I doubt that this fixes the issue but is generally a bad idea.

Do you use `nvm` to manage your node installation? if not you could give it a try, it works fine for me.

As for the error, I'll try to find out a bit later, but more information should help e.g. which version of node and npm you are running. It might be that the dependencies of the workshop are also outdated...

**Comment by marcjansen** [comment]
Issue confirmed with Node 10 & 8. Workshop functional with v6.14.2. As a quick workaround in the meantime you can try to go through the workshop on Node 6.

I will try to see what the root issue is with newer Node versions.

**Comment by marcjansen** [comment]
#34 should fix your error.

**Comment by marcjansen** [comment]
Hey @JakobMiksch , please try again if the following works for you:

```bash
# Create a directory gx-ws and go there …
mkdir -p ~/gx-ws && cd ~/gx-ws
# … grab the zip-archive …
wget https://github.com/geoext/geoext3-ws/archive/master.zip
# … unzip the archive …
unzip master.zip
# … change into the extracted folder
cd geoext3-ws-master
# … install dependencies via npm
npm install
# … start the workshop server
npm start
```

**Comment by JakobMiksch** [comment]
Yes, it works. 
Now I can open the gitbook on `localhost:4000`.
Thanks!
